# Generated by Django 3.1.7 on 2021-05-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210512_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproblemverdict',
            old_name='quizDoneIn',
            new_name='quiz',
        ),
    ]
