# Generated by Django 3.1.7 on 2021-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_userproblemverdict_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproblemverdict',
            name='weight',
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
