# Generated by Django 3.1.7 on 2021-05-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210513_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='official',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionHTML',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
