# Generated by Django 3.1.7 on 2021-05-31 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20210531_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
