# Generated by Django 3.1.7 on 2021-06-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_remove_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='official',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quizWeight',
            field=models.IntegerField(default=100),
        ),
    ]
